/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BurgersList: typeof import('./components/BurgersList.vue')['default']
    DrinksList: typeof import('./components/DrinksList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    List: typeof import('./components/List.vue')['default']
    RibsList: typeof import('./components/RibsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalatsList: typeof import('./components/SalatsList.vue')['default']
    SteaksList: typeof import('./components/SteaksList.vue')['default']
  }
}
